### ISSUE TITLE
Instructions for changing text formatting

### ISSUE THREAD

**Issue by jeffbrl** [jeffbrl/jeffbrl.github.io#2]
Please comment in this issue on how to make the main text on the home page resemble /blog/2017/05/05/business-education.html in terms of font, font size, and line spacing.  Please do not actually make the change. I can experiment with this by myself.

**Comment by onweru** [comment]
I don't quite follow ... which text do you want to change? The one the homepage or the one on the blog?

**Comment by onweru** [comment]
I suppose you are comfortable with basic css. In that case, the styles for the blog articles are split in two files **[critical.css](/_includes/css/critical.css)** and **[posts.css](/_includes/css/posts.css)**. The styles for the site's homepage are in the **[main.css](/_includes/css/main.css)**

In case, you're not comfortable with basic css, I can comment on what rules to experiment with.

**Comment by jeffbrl** [comment]
I know basic CSS and I know how to google. :-) Thank you.
