### ISSUE TITLE
Reduce vertical size of div overlay-mask

### ISSUE THREAD

**Issue by jeffbrl** [jeffbrl/jeffbrl.github.io#7]
On current master branch on desktop client, there's white background visible on the landing page at the bottom without scrolling down. I prefer this as it indicates to the view that there is more to the site by scrolling down. In the test branch, the blue background extends to the bottom of the window. Can you please fix this so that white space is visible. 

I'll examine your commit to see how to do it. That way I can adjust on my own.

**Comment by onweru** [comment]
I made some changes. Check commits 43c0c481 and b68e371
