### ISSUE TITLE
copy button 

### ISSUE THREAD

**Issue by onweru** [jeffbrl/jeffbrl.github.io#8]
I will look into how we can add a copy button on each **config block** in your posts. Is that something you would want?

**Comment by jeffbrl** [comment]
I would want the feature if I can turn the button on or off per code block
in markdown.

**Comment by onweru** [comment]
It can be done but it's hack. For simplicity, let's skip.

**Comment by jeffbrl** [comment]
Sounds good. No hacks. :)
